# Generated by Django 5.2.4 on 2025-08-01 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('books_count', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='publishers/')),
            ],
        ),
    ]
